spring.application.name=Tasks
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=qwerty007
spring.datasource.url=jdbc:postgresql://localhost:5432/ITK


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.initialization-mode=always

server.port=80

spring.kafka.bootstrap-servers = localhost:19092
spring.kafka.producer.key-serializer = org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer = org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.auto.create.topics.enable = true

spring.kafka.admin.fail-fast = true
spring.kafka.properties.retry.backoff.ms = 1000
spring.kafka.properties.reconnect.backoff.ms4 = 1000
spring.kafka.properties.reconnect.backoff.max.ms = 10000

default-page-size=2

