### Получение списка задач

GET localhost/tasks?page=2

### Поиск задачи по Id

GET localhost/tasks/7

### Добавление задачи

POST localhost/tasks
Content-Type: application/json

{
  "name": "name - 11",
  "description": "description - 11",
  "status": "created"
}

### изменение статуса задачи

PUT localhost/tasks/1
Content-Type: application/json

{
  "status": "ok"
}

### Назначение исполнителя задачи

PUT localhost/tasks/4
Content-Type: application/json

{
  "accountId": 1
}

